config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :friends
  get "home/about"
  # root "home#index"
  root "friends#index"


  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friend.rb
class Friend < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :friends
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [ :index, :show ]
  before_action :correct_user, only: [ :edit, :update, :destroy ]

  def index
    @friends = user_signed_in? ? current_user.friends : []
  end

  def show
  end

  def new
    @friend = Friend.new
  end

  def edit
  end

  def create
    @friend = current_user.friends.build(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to @friend, notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to @friend, notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @friend.destroy!
    respond_to do |format|
      format.html { redirect_to friends_path, status: :see_other, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @friend = current_user.friends.find_by(id: params[:id])
    redirect_to friends_path, notice: "Not Authorized!" if @friend.nil?
  end

  private

  def set_friend
    @friend = Friend.find(params[:id])
  end

  def friend_params
    params.require(:friend).permit(:first_name, :last_name, :email, :phone, :twitter)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def about 
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class:"field form-group" >
    <% form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name , class: "form-control" , placeholder:"First Name" %>
  </div>

  <div class:"field form-group">
    <% form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name , class: "form-control" , placeholder:"last Name" %>
  </div>

  <div class:"field form-group">
    <% form.label :email, style: "display: block" %>
    <%= form.text_field :email , class: "form-control" , placeholder:"Email" %>
  </div>

  <div class:"field form-group">
    <% form.label :phone, style: "display: block" %>
    <%= form.text_field :phone , class: "form-control" , placeholder:"Phone#" %>
  </div>

  <div class:"field form-group">
    <% form.label :twitter, style: "display: block" %>
    <%= form.text_field :twitter , class: "form-control" , placeholder:"Twitter" %>
  </div>

  <div class:"field form-group">
    <% form.label :twitter, style: "display: block" %>
    <%= form.number_field :user_id , id: :friend_user_id , class: "form-control" , value: current_user.id, placeholder:"User ID" , type: :hidden %>
  </div>
 
  <div>
    <%= form.submit  class:"btn btn-secondary" %>
  </div>
<% end %>

app/views/friends/_friend.html.erb
<div id="<%= dom_id friend %>">
  <p>
    <strong>First name:</strong>
    <%= friend.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= friend.last_name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= friend.email %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= friend.phone %>
  </p>

  <p>
    <strong>Twitter:</strong>
    <%= friend.twitter %>
  </p>

</div>

app/views/friends/edit.html.erb
<% content_for :title, "Editing friend" %>

<h1>Editing friend</h1>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Show this friend", @friend , class:"btn btn-primary" %> |
  <%= link_to "Back to friends", friends_path , class:"btn btn-primary" %>
</div>

app/views/friends/index.html.erb
<% if user_signed_in? %>
  <p style="color: green">
  <% content_for :title, "Friends" %>

  <h1>Friends</h1>

  <%= link_to "New friend", new_friend_path , class:"btn btn-success mb-3" %>

  <table class="table table-bordered table-striped table-hover">
    <thead class="table-dark">
      <tr>
        <th>First Name</th>
        <th>Email</th>
        <th>Phone</th>
        <th>Twitter</th>
        <th>User ID</th>
        <th colspan="3">Actions</th>
      </tr>
    </thead>

    <tbody>
      <% @friends.each do |friend| %>
        <tr>
          <td><%= friend.first_name %> <%= friend.last_name %></td>
          <td><%= friend.email %></td>
          <td><%= friend.phone %></td>
          <td><%= friend.twitter %></td>
          <td><%= friend.user_id %></td>
         
          <td>
            <%= link_to "Show", friend, class: "btn btn-sm btn-primary" %>
          </td>
          <td>
            <%= link_to "Edit", edit_friend_path(friend), class: "btn btn-sm btn-warning" %>
          </td>
          <td>
            <%= button_to "Delete", friend_path(friend.id) , method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-sm btn-danger" %>
          </td>
          
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= link_to "New friend", new_friend_path , class:"btn btn-primary" %>
<% else %>
  <h1>Hello Hassan!</h1>
  This is my first webpage.
<% end %>

app/views/friends/new.html.erb
<% content_for :title, "New friend" %>

<h1>Add friend</h1>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Back to friends", friends_path , class:"btn btn-primary" %>
</div>

app/views/friends/show.html.erb
<div class="card p-4 shadow mb-4">
  <h1 class="display-4 mb-3"><%= @friend.first_name %> <%= @friend.last_name %></h1>
  <p class="lead">Email: <strong><%= @friend.email %></strong></p>
  <p class="lead">Phone: <strong><%= @friend.phone %></strong></p>

  <hr class="my-4">

  <div class="d-flex gap-2 flex-wrap">
    <%= link_to "✏️ Edit this friend", edit_friend_path(@friend), class: "btn btn-warning" %>
    <%= link_to "📋 Back to friends", friends_path, class: "btn btn-secondary" %>
    <%= button_to "🗑️ Destroy this friend", @friend, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger" %>
  </div>
</div>

app/views/home/_header.html.erb
<ul class="nav nav-pills">

  <li class="nav-item">
   <%= link_to "Friends App" , root_path , class:"nav-link active" %>
  </li>

  <li class="nav-item">
   <%= link_to "About us" , home_about_path , class:"nav-link"%>
  </li>

  <li class="nav-item">
   <%= link_to "Friends" , friends_path , class:"nav-link" %>
  </li>

  <% if user_signed_in?%>
   <li class="nav-item">
     <%= link_to "Add Friend" , new_friend_path , class:"nav-link" %>
   </li>

   <li class="nav-item">
     <%= link_to "Edit Profile" , edit_user_registration_path , class:"nav-link " %>
   </li> 

   <li class="nav-item">
     <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: "nav-link btn btn-sm btn-primary" %>
   </li>

  <% else %>
   <li class="nav-item">
     <%= link_to "Sign up" , new_user_registration_path , class:"nav-link " %>
   </li>

   <li class="nav-item">
     <%= link_to "Sign in" , new_user_session_path , class:"nav-link " %>
   </li>
  <% end %> 

  
</ul>

app/views/home/about.html.erb
<h1>About Us</h1>

app/views/home/index.html.erb
<h1>Hello Hassan!</h1>
This is my first webpage.

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
     
    <title>Friends App</title>

  </head>
  <body>
    <%= render 'home/header' %>
    <div class="container">
      <% if notice %>
       <%= render 'layouts/alerts' %>
      <% end %>
      <br/>
      <%= yield %>
    </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

    <!-- Option 2: jQuery, Popper.js, and Bootstrap JS
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
    -->
  </body>
</html>